### ISSUE TITLE
Name FunctionObject in a more specific way

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#100]
Matt Calabrese wrote:

> I suggest not using the name FunctionObject for something that is only
> callable with a const object. This is a little more specific that what most
> people refer to as a function object in C++ and may cause confusion.

**Comment by pfultz2** [comment]
I am thinking of describing it as `ConstFunctionObject`, this also affects the `Callable` concept as well.

**Comment by viboes** [comment]
I'm for ConstFunctionObject as you have also MutableFunctionObject.
