### ISSUE TITLE
[QuickStart.Tuples] Misleading use of decltype to constrain lambda?

### ISSUE THREAD

**Issue by ldionne** [pfultz2/Fit#131]
In the quick start, section Tuples, there's this piece of code:

```c++
FIT_STATIC_LAMBDA_FUNCTION(print) = conditional(
    [](const auto& x) -> decltype(std::cout << x, void())
    {
        std::cout << x << std::endl;
    },
    [](const auto& range) -> decltype(std::cout << *adl::adl_begin(range), void())
    {
        for(const auto& x:range) std::cout << x << std::endl;
    },
    [](const auto& tuple) -> decltype(for_each_tuple(tuple, identity), void())
    {
        return for_each_tuple(tuple, [](const auto& x)
        {
            std::cout << x << std::endl;
        });
    }
);
```

Why do you use `decltype(for_each_tuple(...))`? If I'm not mistaken, if no other branch of the conditional is taken and the argument is not a tuple, this will cause a hard error inside of `for_each_tuple`, regardless of the fact that `decltype(for_each_tuple(...))` was used to "constrain" the lambda. So basically my impression is that this appearance of `decltype(for_each_tuple(...))` is both useless and misleading. Did I miss something?

**Comment by pfultz2** [comment]
Good point, so `for_each_tuple` probably should be defined as:

```cpp
FIT_STATIC_LAMBDA_FUNCTION(for_each_tuple) = [](const auto& sequence, auto f) FIT_RETURNS(unpack(by(f))(sequence));
```

Or I should just drop the trailing decltype on the last branch. I think dropping the trailing decltype is the better option for the quick start guide, as it keeps it simple, and doesn't need the identity dance.

**Comment by ldionne** [comment]
Whatever feels right, I just wanted to point the issue out.

**Comment by pfultz2** [comment]
Yea, thanks for the feedback, I hope you have time to leave a review.

**Comment by ldionne** [comment]
Yes, I'm doing this right now. Sorry for being so late.
