### ISSUE TITLE
[BasicConcepts.Metafunction] Circular definition

### ISSUE THREAD

**Issue by ldionne** [pfultz2/Fit#136]
When defining the _Metafunction_ concept, it is written

> Given
>
> - `f`, a metafunction
> - `args...`, any suitable type, which may be empty
> [...]

However, I think defining `f` as a _metafunction_ is incorrect, because this is specifically the term we're trying to define. Of course this is clear if you already know what a metafunction is, but then there's no point in defining the concept :-).

I would suggest saying something like 

> Given
>
> - `f`, a type or a template

which is more accurate as to the nature of `f`.

**Comment by ldionne** [comment]
The same comment applies to `MetafunctionClass` as well, except `f` should be defined as being a type and not a template.

**Comment by pfultz2** [comment]
I think this is a good idea, thanks.
