### ISSUE TITLE
[Adaptors.lazy] Are the arguments captured by value or by reference?

### ISSUE THREAD

**Issue by ldionne** [pfultz2/Fit#138]
The example for `lazy` says

> ```c++
> auto add = [](auto x, auto y) { return x+y; };
> auto increment = lazy(add)(_1, 1);
> assert(increment(5) == 6);
> ```

I am wondering whether `1` in `lazy(add)(_1, 1)` is captured by value (and moved into some object), or if it's captured by reference. Saying that `lazy` is like `std::bind` suggests that it is captured by value, but it would be nice to state this explicitly, like you state explicitly for `fit::partial`.

**Comment by pfultz2** [comment]
They do capture by value like `std::bind` and `partial`. I will add a note about that.
