### ISSUE TITLE
[Adaptors.lazy] Can we capture elements by reference with std::ref?

### ISSUE THREAD

**Issue by ldionne** [pfultz2/Fit#139]
__Note: I tried submitting this issue already, but it appears that GitHub just dropped it. Please ignore if this causes the issue to be submitted twice.__

The reference for `fit::partial` says the following (emphasis mine):

> The `partial` function adaptor allows partial application of the function. If the function can not be called with all the parameters, it will return another function. It will repeatedly do this until the function can finally be called. __By default, `partial` captures all of its variables by value, just like bind. `std::ref` can be used to capture references instead.__

Is it possible to do the same with `fit::lazy`, i.e. is it possible to write:

```c++
auto add = [](auto x, auto y) { return x+y; };
std::string s = "s";
auto pluralize = fit::lazy(add)(fit::_1, std::ref(s));
assert(pluralize("toast") == "toasts");
```

If not, then it would be useful to make it possible. Otherwise, I think this should be documented.

**Comment by pfultz2** [comment]
> Is it possible to do the same with fit::lazy, i.e. is it possible to write:

Yes this is already possible. I should make it more clear in the docs.
