### ISSUE TITLE
Consider providing a master header

### ISSUE THREAD

**Issue by ldionne** [pfultz2/Fit#143]
It would be nice to provide a master `fit.hpp` or `fit/fit.hpp` header that includes everything in the library. While it is usually nuts to use this master header in actual production code, it is invaluable when trying the library out for new users. Nobody wants to spend time figuring out which headers to include.

**Comment by pfultz2** [comment]
I probably should convert [this](https://github.com/pfultz2/Fit/blob/master/example/example.h) into a master header.

**Comment by pfultz2** [comment]
This is actually fixed in commit `9f4fcb7cf9a2f65d867992edf58a03aece15bb61`.

**Comment by viboes** [comment]
IIUC this file is generated. How would you generate it with bjam?

**Comment by pfultz2** [comment]
Its not generated by the build system. Although that would be good idea, I would need to figure out how to do that using bjam. For now, I create this manually.
