### ISSUE TITLE
#include <functional> is missing in unwrap.h

### ISSUE THREAD

**Issue by bwoods** [pfultz2/Fit#2]
Needed for the [`std::reference_wrapper`](http://en.cppreference.com/w/cpp/utility/functional/reference_wrapper) used by `unwrap_reference`. 

> **Compiler**:
> Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
> Target: x86_64-apple-darwin14.1.0
> Thread model: posix

**Comment by pfultz2** [comment]
Added header, thanks.
