### ISSUE TITLE
It would be useful to have a section on how to run the test

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#23]

**Comment by pfultz2** [comment]
The test can be run by building the `check` target. So either doing `make check` if you are using make, or just doing `cmake --build build --target check`(assuming you build directory is `build`) for any build system.

**Comment by viboes** [comment]
Please could you add a section.

I have cmake 2.8.12.2 and I'm getting
```
new-host:Fit viboes$ cmake --build build --target check
Error: could not load cache
new-host:Fit viboes$ cmake
cmake version 2.8.12.2
```

Is this error due to the fact that you require cmake 3. ?

**Comment by pfultz2** [comment]
I dont know. What is the output of the running cmake the first time?

**Comment by viboes** [comment]
It is not the first time. I use it with other projects. Do we need version cmake 3.0 or you have tested only with this version?

**Comment by bcachet** [comment]
`couldn't load the cache` means CMake hasn't been run to generate the build artifact.

To run the tests you have to:

```bash
mkdir build
cd build
cmake ..
cd ..
cmake --build build --target check
```

**Comment by viboes** [comment]
Sorry, I don't use to use cmake.

I've changed the cmake version to 2.8 and I'm getting compiler errors after 
```
cmake --build build --target check
```
How I can choose the compiler to use?

**Comment by viboes** [comment]
I have reached to select the compiler and almost everything is working. 
I'm using gcc-5.1 c++11 or c++14.

I'm getting this error however

```
In file included from /Users/viboes/github/Fit/test/capture.cpp:1:0:
/Users/viboes/github/Fit/test/capture.cpp: In member function ‘void test_6::operator()() const’:
/Users/viboes/github/Fit/test/test.h:79:36: erreur: non-constant condition for static assertion
 #define FIT_STATIC_TEST_CHECK(...) static_assert(__VA_ARGS__, FIT_STRINGIZE(__VA_ARGS__))
                                    ^
/Users/viboes/github/Fit/test/capture.cpp:8:5: note: in expansion of macro ‘FIT_STATIC_TEST_CHECK’
     FIT_STATIC_TEST_CHECK(fit::capture(1, 2)(binary_class())() == 3);
```
and other similar

```
The following tests FAILED:
	  6 - capture (Not Run)
	  7 - combine (Not Run)
	 16 - function (Not Run)
	 21 - infix (Not Run)
	 29 - partial (Not Run)
	 30 - pipable (Not Run)
```

Do you have an idea what is going wrong?

**Comment by bcachet** [comment]
If you want to select a new compiler, you have to generate new build artifact. That means that you should almost always clean the initial destination of your build artifacts.

```
rm -rf build
mkdir -p build
cd build
CXX=clang++ cmake ..
cd ..
cmake --build build --target check
```

**Comment by bcachet** [comment]
@viboes I have tested with success both clang-700.0.72 and gcc 5.2.0

**Comment by viboes** [comment]
@bcachet Thanks a lot, but even after rm I get the same error.

**Comment by pfultz2** [comment]
I just add gcc 5.1 to the travis CI. It looks like it fails. I am going to look into this.

**Comment by pfultz2** [comment]
Well it looks like gcc 5.1 won't be supported at all, it just has too many problems. Also, right now, I haven't found a way to add gcc 5.2 to Travis, either. So i am not regularly running the tests for gcc 5.2.
