### ISSUE TITLE
C++11 or C++14 library?

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#24]
In http://fit.readthedocs.org/en/latest/index.html I  can see
"Fit is a header-only C++11 library"
" Fit takes advantages of modern C++11/C++14 features"

Does Fit need some C++14 support? If suspect that not because it is a C++11library.

This is confusing.

**Comment by pfultz2** [comment]
The minimum requirement is C++11, but there are a few things that require C++14(like [`FIT_LIFT`](http://fit.readthedocs.org/en/latest/lift/index.html)).

**Comment by viboes** [comment]
I have no problem with that.  This must however be clarified.

**Comment by pfultz2** [comment]
This is updated in the latest updates to the docs.
