### ISSUE TITLE
What "does not try to implement a functional language in C++" exatly mean?

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#25]

**Comment by pfultz2** [comment]
This is too contrast it too say FC++ or Boost.Phoenix, which reimplements C++ in a functional way. As such, the functions in Fit do not curry by default, nor is there special functions for control flow(like [here](http://www.boost.org/doc/libs/1_59_0/libs/phoenix/doc/html/phoenix/modules/statement.html)). Does that make sense?

**Comment by viboes** [comment]
I believe them did that because we didn't have lambdas.
BTW some works respect to FC++ and Boost.Phoenix are missing in the documentation. During the review you will need to show a comparison with these libraries.

**Comment by pfultz2** [comment]
This is updated in the latest updates to the docs.
