### ISSUE TITLE
Must the operator() requireded to be declared const?

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#27]

**Comment by pfultz2** [comment]
Yes, but the mutable adaptor can be used for functions that require mutations.

**Comment by viboes** [comment]
But you say that the `mutable` should not be used

**Comment by pfultz2** [comment]
In general, mutable function objects(ie with non-const call operator) are a bad idea, and should be avoided. However, if you really feel you need a mutable function object(perhaps you are given a function object from another library that didn't put `const`) then the mutable adaptor can be used.
