### ISSUE TITLE
Not clear how to make a function object pipable

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#28]
It is not clear if the two previous lines are needed to make `sum` pipable.

```c++
FIT_STATIC_FUNCTION(sum) = sum_f();
```
and
```c++
const constexpr pipable_adaptor<sum_f> sum = {};
```
It would be great to have a link to the complete example in the example/tutorial directory.

BTW, why `const constexpr`?

**Comment by pfultz2** [comment]
I have rewritten the quick start guide to make this clearer.
