### ISSUE TITLE
How FIT_STATIC_FUNCTION is related to static_const from Eric?

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#30]

**Comment by viboes** [comment]
Has Boost.Hana something related?

The same question for `FIT_STATIC_LAMBDA`

**Comment by ldionne** [comment]
No, Hana does not have anything similar to `FIT_STATIC_FUNCTION`.

**Comment by pfultz2** [comment]
On compilers that support it, it uses the `static_const` technique from Eric Niebler. In the future, hopefully, it will use an inline variable instead. `FIT_STATIC_LAMBDA` and `FIT_STATIC_LAMBDA_FUNCTION` are not related to Eric Niebler's `static_const`. I wrote a blog post about it [here](http://pfultz2.com/blog/2015/05/31/unique-address/) that goes into more detail about some the techniques used.

**Comment by viboes** [comment]
I believe that then you can describe it, FIT_STATIC_FUNCTION should refer to the Eric proposal and FIT_STATIC_LAMBDA_FUNCTION should refer to your post.

**Comment by pfultz2** [comment]
I added links to Eric Niebler's n4381.

**Comment by viboes** [comment]
Have add a link to your blog?
