### ISSUE TITLE
Add a reference to P0051 - C++ overload function

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#31]
This proposal is related to `match`/`conditional`. A reference would be welcome. 

Note that P0051 - C++ match function is related to visitation.

**Comment by pfultz2** [comment]
I don't see how thats related at all.

**Comment by viboes** [comment]
What?

**Comment by pfultz2** [comment]
Oops, I think I saw the wrong paper. The link to the paper is [here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0051r0.pdf) for future reference.
