### ISSUE TITLE
The use of FIT_STATIC_LAMBDA_FUNCTION for match/conditional constraints the implementation

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#32]
IIUC match and conditional return today a lambda, but they could as well return a function object in the future, isn't it?

I will replace the macro `FIT_STATIC_LAMBDA_FUNCTION` by a more specific one,e.g. FIT_STATIC_CONDITIONAL_FUNCTION. 
```c++
FIT_STATIC_LAMBDA_FUNCTION(print) = conditional( ...);
The same for match.

**Comment by pfultz2** [comment]
The `FIT_STATIC_LAMBDA_FUNCTION` is used because lambdas are passed to `fit::conditional`, but if function objects were passed then `FIT_STATIC_FUNCTION` can be used instead.

**Comment by viboes** [comment]
Do you mean that we can use both? If yes, this is not clear in the documentation.

**Comment by pfultz2** [comment]
I don't understand why that isn't clear as the examples for both `conditional` and `match` use function objects. Also, they are not related at all to the `FIT_STATIC_*` macros, and the documentation makes no reference to them either.
