### ISSUE TITLE
It is not clear why the user would like to statically initialized at compile time

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#33]
I would suggest first how the user can use the library when it doesn't need to statically initialize at compile time and only then show when it is useful to do it, the current limitation of the language C++11/C++14 and how Fit solves the issue.

**Comment by pfultz2** [comment]
From the docs:

> However, we want to statically initialize it(ie initialize it at compile-time) to avoid the static initialization order fiasco.

Static initialization is only required for global function objects because the static initialization order fiasco only affects global variables.

**Comment by viboes** [comment]
I understand the problem of initialization,but starting with examples that solve this problem seems not good for a tutorial and less yet for a quick start.

**Comment by pfultz2** [comment]
It is trying to show the best practice pattern for initialing global function objects. The user should always initialize them that way. If the user wants to understand why, they can read up on static initializaion order fiasco.

**Comment by viboes** [comment]
I was just a suggestion. The reading of the introductory material is hard with all this specific cases.

**Comment by pfultz2** [comment]
Closing this for now, since the documentation has been restructured.
