### ISSUE TITLE
Rename macro REQUIRES by FIT_REQUIRES

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#35]

**Comment by ldionne** [comment]
Actually, shouldn't it be `BOOST_FIT_REQUIRES` if the library is to be Boostified?

**Comment by viboes** [comment]
Of course, but I don't know if we want to require the change of the namespace and the prefixes  before the review. What do you think? Paul? Do you plan to do this before the review?

**Comment by pfultz2** [comment]
`REQUIRES` is not defined by the library, and is only defined in the example. Although, it might be better to change the example so it doesn't require using `enable_if`.

**Comment by viboes** [comment]
Agreed.

**Comment by pfultz2** [comment]
This is not applicable anymore with the latest docs.
