### ISSUE TITLE
define what a function is before defining what is a function adaptor

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#37]
I believe that you need to define before what a function is before defining what is a function adaptor.

"A function adaptor takes a function(or functions) and returns a new function "

Is it a Callable?

**Comment by pfultz2** [comment]
That is left to each adaptor to define. Most adaptors use `FunctionObject`, however, there is a few that are different. That is why I just use function there.

**Comment by viboes** [comment]
So there is no concept of adaptor :(

**Comment by pfultz2** [comment]
There is almost a concept definition of an adaptor in the overview, at least to show how they work. However, there is no concept definition of an adaptor because each adaptor fulfills the concept of a `FunctionObject`. Just like iterator adaptors fulfill the concept of an iterator.
