### ISSUE TITLE
[if_] Clarify the documentation

### ISSUE THREAD

**Issue by ldionne** [pfultz2/Fit#41]
The documentation of `if_` is not clear to me. It says

> The if_ function decorator applies a boolen condition to the function.

However, it seems to me like what it does is make the function callable only when the predicate is satisfied, or something like that. Also, there's a typo in the above quote (`boolen`).

**Comment by pfultz2** [comment]
Ah yea, that is a much better description. Thanks.

**Comment by viboes** [comment]
It would be great to close the issues by referencing the commit that fixed them
