### ISSUE TITLE
always(reference_wrapper<T>) overload

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#42]
`always_ref(v)` could be equivalent to `always(ref(v))`with an specialization for 

```c++
template<class T>
always(reference_wrapper<T> value);
```

**Comment by ldionne** [comment]
+1, I think this is a great idea. It sucks to have to include the whole of `<functional>` just for `std::reference_wrapper`, but meh.

**Comment by viboes** [comment]
You are right Louis, this is C++ ;-)

**Comment by pfultz2** [comment]
`fit::always` already unwraps the reference. `always_ref` is provided because it is used in many places in the library, and it helps reduce down the compile time overhead(it seems unnecessary to always wrap and unwrap the reference).

**Comment by viboes** [comment]
this must be precise in the documentation.
