### ISSUE TITLE
It is not clear why always(n) is a variadic function

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#45]
Some design rational would be welcome

**Comment by pfultz2** [comment]
From the definition:

> The always function returns a function object that will always return the value given to it, no matter what parameters are passed to the function object.

As such, it couldn't be anything other than variadic function.

**Comment by viboes** [comment]
I understand that given the definition the function must be variadic ;-)
What I don't understand is why the always function need any parameter.
For me always should return a nullary function. I understand that a variadic function is more general

An example showing the use on a variadic context would be welcome.

**Comment by pfultz2** [comment]
The `always` function swallows the parameters, and returns the value. This is useful in many contexts. An example from the standard library, say we want to count all elements in a range, then we could implement this using `std::count_if`:

```cpp
template<class Iterator, class T>
auto count(Iterator first, Iterator last)
{
    return std::count_if(first, last, always(true));
}

```

If `always` was only nullary then this wouldn't be possible.

**Comment by viboes** [comment]
Great, good example to add.

Vicente
