### ISSUE TITLE
Consider providing a FindFit.cmake module

### ISSUE THREAD

**Issue by ldionne** [pfultz2/Fit#48]
I find it useful to have a FindXXX.cmake module for easily adding a library as a dependency in a CMake project. If you are interested in adding this, you can look at [Hana's](https://github.com/ldionne/hana/blob/bd974d6ad8be85fc1b7d73d206a756da2b5140cc/cmake/FindHana.cmake).

**Comment by viboes** [comment]
I have not reached to run the test. Is the constraint version 3 a real one?

**Comment by pfultz2** [comment]
It already provides a pkg-config file.

**Comment by ldionne** [comment]
Paul, how does the pkg-config file works? I'm on OS X; does that help me, and if so, how?

**Comment by pfultz2** [comment]
After you install Fit, you can run `pkg-config fit --cflags` for compiler flags and `pkg-config fit --libs` for linker flags(even on OS X). Inside of cmake you can just use the `FindPkgConfig` module:

```
find_package(PkgConfig)
pkg_check_modules(MY_PKGS REQUIRED fit)
```

And then you can link your executable like this:

```
add_executable(myexe ${SOURCES})
target_link_libraries(myexe ${MY_PKGS_LDFLAGS})
target_include_directories(myexe PUBLIC ${MY_PKGS_INCLUDE_DIRS})
target_compile_options(myexe PUBLIC ${MY_PKGS_CFLAGS_OTHER})
```

Right now, Fit is header only, so the `MY_PKGS_LDFLAGS` is not necessary, but if in the future Fit were to depend on another library that wasn't header-only, this would continue to work correctly, so its there for completeness.
