### ISSUE TITLE
lift - signature and example missing

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#57]

**Comment by pfultz2** [comment]
There is a signature and example in the documentation. I am not sure what you are referring to.

**Comment by viboes** [comment]
The section is called lift and so I'm looking for a lift function.
There are macros `FIT_LIFT` but not a `lift` function.

**Comment by pfultz2** [comment]
There is no `lift` function.

**Comment by viboes** [comment]
So the section should be renamed so that users like me are not looking for something that doesn't exists.

**Comment by viboes** [comment]
#80
