### ISSUE TITLE
Do we need to know explicitly the result of the adaptors?

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#60]
I'm wondering if we need to name the result of the adaptors, or just say that it is an unspecified function with a specific signature that behaves as .... 

What is the advantage to giving it a name? 

Giving a name to the result type would imply to add the description of all of its operations.

**Comment by pfultz2** [comment]
Yes, because you can just use the class form of them. This is useful when you are just dealing with types. Also, the static function adaptors are all class-based so it makes it easier work with them as well.

**Comment by viboes** [comment]
Then you need to define more explicitly the interface of the adaptors, which operations are allowed, the semantic of each operation, ...
