### ISSUE TITLE
capture versus partial

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#63]
```
capture(xs...)(f)(ys...) <==> f(xs..., ys...)
```
Another way is to define it as
```
capture(xs...)(f) <==> partial(f, xs...)
```

Is there a difference in performances, between the 3 expressions?

```
capture(xs...)(f)(ys...) <==> f(xs..., ys...) <==> partial(f, xs...)(ys...)
```

BTW, the example would clearer if you use different number 
```
assert(f(5, 8) == std::make_tuple(std::make_pair(1, 5), std::make_pair(2, 8)));
```

or even different types.

**Comment by pfultz2** [comment]
There not the same. It is **almost** like this:

```cpp
capture_decay(xs...)(f)(ys...) <==> partial(f)(xs...)(ys...)
```

However, `partial` allows for continual partial application. So if `partial(f)(xs...)(ys...)` is not callable, you will always get another function back, whereas if `capture_decay(xs...)(f)(ys...)` is not callable, you will get a compile error. Plus, with `capture` you have three different options of how variables are captures. With `partial` it is always uses `fit::decay` which is the safest option.

**Comment by viboes** [comment]
Any comment about the performances?

**Comment by pfultz2** [comment]
Well `capture_decay` and `partial` there should be no difference in runtime performance since they both copy the parameters, however, `capture` and `capture_forward` can be used to avoid extraneous copies.
