### ISSUE TITLE
indirect - what happens if the parameter is nullptr

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#66]
```c++
unique_ptr<sum> psum;
int r = indirect(psum)(3,2);
```

It seems that there is a precondition missing. It shoul dbe more explicit the operation used on the parameter, in this case `operator*()` I guess.

`Applicatives` have a similar and safer function that returns another Applicative having the same type-constructor.
```
(<*>) :: f (a -> b) -> f a -> f b
```
if f is also a `Monad` `<*>` is equal to `ap`
```
auto r = ap(psum, make_unique(3,2)); // decltype x is unique_ptr<int>
```

As defined, the parameter should be a model of a `PossiblyNull` or `PossyblyValued` concept supporting the dereference function.

**Comment by pfultz2** [comment]
It is undefined behavior to dereference null.

> As defined, the parameter should be a model of a PossiblyNull

Dereferencibility is only required, since, you can pass a Dereferenceable object that is never null. That is being able to dereference an object is unrelated to whether it can be null or not, and `fit::indirect` doesn't ever check for something null.

**Comment by viboes** [comment]
Wondering if some clarifications can added to help the user to understand that this case is UB.

**Comment by pfultz2** [comment]
I added a semantic section to make this clearer.
