### ISSUE TITLE
The proposed std::invoke and std::apply - two key functions to make the implementation much simpler

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#67]
The implementation would be much more simpler if we have an `invoke` function that follows the `INVOKE` protocol.

The `std::apply` C++14 function would help also as well but it shoul dbe INVOKE compatible.

Finally a `is_callable` trait will complete the picture.

Unfortunately the function in Boost.Thread detail is broken at least for C++98 compilers.

See 
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3915.pdf
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4169.html 
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4170.html
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0077r0.html

**Comment by K-ballo** [comment]
> The std::apply C++14 function would help also as well but it shoul dbe INVOKE compatible

It's  `std::experimental::apply` and is in the Library Fundamentals TS. It's now `INVOKE` based thanks to [LWG2418](http://cplusplus.github.io/LWG/lwg-defects.html#2418).

**Comment by pfultz2** [comment]
I don't see how it makes the "implementation" simpler.

**Comment by pfultz2** [comment]
`fit::apply` uses the `INVOKE` operator.
