### ISSUE TITLE
lazy - should support any Callable

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#68]
What is the real functionality of this function other than store the passed function and been able to call it later on?

**Comment by pfultz2** [comment]
For the same reason you would use lambda expression(or `std::bind`), except `fit::lazy` is constexpr friendly. Also, `std::mem_fn` can be used for pointer to member functions.

**Comment by viboes** [comment]
Yes, but binding a function with no arguments doesn't add nothing and

```c++
[](auto a, auto b) { return f(a,b)
```

doesn't add nothing to `f`.

I'm missing something trivial and I don't know what is it.

**Comment by pfultz2** [comment]
> Yes, but binding a function with no arguments doesn't add nothing

Where is this happening?

**Comment by pfultz2** [comment]
Closing this since I haven't heard anything back about this.
