### ISSUE TITLE
reveal - add an example of compiler error with and without the use of reveal.

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#72]

**Comment by pfultz2** [comment]
Well, I show the errors [here](http://pfultz2.com/blog/2015/02/27/error-messages/), except that example relies on the Tick library. I would like to get the patch in for clang before showing the error messages, as the patch helps improve error reporting a lot.

**Comment by pfultz2** [comment]
The review for the patch on clang is [here](http://reviews.llvm.org/D8309).

**Comment by tzlaine** [comment]
+1 to quoting error messages in your docs, even if they change in Clang later.

**Comment by pfultz2** [comment]
So I added a sample of the error message as well as a some more info about doing custom failure reporting with the `reveal` adaptor. I'll update it later with the error messages from the new Clang.
