### ISSUE TITLE
reverse_compress - associativity issue

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#73]
right fold is right associative and the function has the signature `f:: A  B -> B` while left fold is left associative and the function has signature `f:: A  B -> A`. A and B are the same and the function is commutative there is no difference, but I believe the need for the difference is to take care of this non-commutative cases.

```
foldr f z []     = z
foldr f z (x:xs) = x `f` foldr f z xs

foldl f z []     = z
foldl f z (x:xs) = let z' = z `f` x 
                   in foldl f z' xs
``` 

See https://wiki.haskell.org/Foldr_Foldl_Foldl' for more details.

```c++
assert(reverse_compress(f, z)(x, xs...) == f(reverse_compress(f, z)(xs...), x));
`

should be
```c++
assert(reverse_compress(f, z)(x, xs...) == f(x, reverse_compress(f, z)(xs...)));
```

**Comment by pfultz2** [comment]
Its called reverse, so that the same binary operator will happen in reverse with `reverse_compress`, that is:

```cpp
assert(fit::compress(_+_, std::string())("Hello", "-", "World") == "Hello-World");
assert(fit::reverse_compress(_+_, std::string())("Hello", "-", "World") == "World-Hello");
```

If I used right associativity as you suggest, then they both would give the same result, which is not desired.

**Comment by viboes** [comment]
Does this mean that we need an additional `compress_right`?

**Comment by pfultz2** [comment]
> Does this mean that we need an additional compress_right?

For what?
