### ISSUE TITLE
capture - more description is needed to understand the differences

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#77]

**Comment by pfultz2** [comment]
What differences?

**Comment by viboes** [comment]
The differences between the 3 capture functions.

**Comment by pfultz2** [comment]
I guess it would be better to use the descriptions from `fit::pack`.

**Comment by viboes** [comment]
Humm, what is the difference between capture and pack?

**Comment by pfultz2** [comment]
Like this:

```cpp
assert(pack(xs...)(f) == f(xs...));
assert(capture(xs...)(f)(ys...) == f(xs..., ys...));
```

Those are the semantics side by side. `fit::capture` uses `fit::pack` and `fit::pack_join`, like this:

```cpp
assert(capture(xs...)(f)(ys...) == pack_join(pack(xs...), pack(ys...))(f));
```

`fit::pack` is used by a lot of adaptors when the parameters need to be stored and invoked later.

**Comment by viboes** [comment]
OK I see, so if `f` has `n` parameters 

```
capture(x1, ..., xn)(f)() ==   pack(x1, ..., xn)(f)
```

You need to describe the differences between the different version of `pack`.

**Comment by pfultz2** [comment]
> You need to describe the differences between the different version of pack.

I do, already, but I can use the same description for `capture`, because I think the descriptions for `fit::pack` are better. Perhaps not. What do you think?

**Comment by viboes** [comment]
I know that it takes some time but I'm for the kind of description th standard use. E.g.
```
template<class... Types>
constexpr tuple<VTypes...> make_tuple(Types&&... t);
```
Let `Ui` be `decay_t<Ti>` for each `Ti` in `Types`. Then each `Vi` in `VTypes` is `X&` if `Ui `equals `reference_wrapper<X>`, otherwise `Vi` is `Ui`.
Returns: `tuple<VTypes...>(std::forward<Types>(t)...)`.

BTW, can `pack/pack_perfect/pack_decay` be defined in function of `make_tuple/forwards_as_tuple/tie'.
How are they related?

For consistency with the standard, shouldn't `pack_join` be named `pack_cat`?

**Comment by pfultz2** [comment]
> I know that it takes some time but I'm for the kind of description th standard use.

I will have to think about that. Right now, the type returned from `pack` is unspecified type.

> BTW, can pack/pack_perfect/pack_decay be defined in function of `make_tuple/forwards_as_tuple/tie'.

Well `pack_decay` is like `make_tuple`, and `pack_forward` is like `forward_as_tuple`. There is no `tie` equivalent. `pack` doesn't store any rvalue references, and is in general a good choice for good performance and avoiding dangling references. That is why it is given the shortest name.

All these apply to the `capture` overloads as well. Actually, capture defers to the corresponding pack function.

> For consistency with the standard, shouldn't pack_join be named pack_cat?

It is not exactly the same. Plus, it sounds funny.

**Comment by pfultz2** [comment]
I change the description.
