### ISSUE TITLE
repeat - what is the rationale of using integral_contant as parameter?

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#78]

**Comment by pfultz2** [comment]
Actually, I would like to support runtime values in the future. I used an `integral_constant` to make it consistent with `repeat_while`. Using `integral_constant` allows stopping compilation of the function when repeat stops, which can avoid compilation errors or overflows. I am going to keep this issue open as reminder to implement this for runtime integrals.

**Comment by viboes** [comment]
I understand the compile-time advantage, but why `ìntegral_constant` and not just an `int`?

**Comment by pfultz2** [comment]
`repeat` now supports integrals.
