### ISSUE TITLE
tap - incoherency

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#79]
incoherency between declaration
```c++
template<class T, class F>
pipable constexpr T tap(T&& x, const F& f);
```

and usage

```c++
int r = 1 | sum(2) | tap([](int i) { std::cout << i; }) | sum(2);
```

**Comment by pfultz2** [comment]
How is that incoherent?

**Comment by viboes** [comment]
The `tap` function used in the pipe expression has one parameter, while the declaration has two parameters.

**Comment by pfultz2** [comment]
> The tap function used in the pipe expression has one parameter, while the declaration has two parameters. 

It has two since its pipable. Pipable functions can either be called as `f(x, y)` or `x | f(y)`. The example uses the piped form to show its usefulness in piped expressions as well. The signature annotates it as pipable, as well as the documentation says it pipable also.

**Comment by viboes** [comment]
What I see is that `tap`with two arguments return a pipable, but I don't see any `tap`function taking one argument. 

The implementation os
```
namespace detail {

struct tap_f
{
    template<class T, class F>
    constexpr T operator()(T&& x, const F& f) const
    {
        return f(x), fit::forward<T>(x);
    }
};

}

FIT_DECLARE_STATIC_VAR(tap, pipable_adaptor<detail::tap_f>);
```

so tap is not a template function having two arguments that return a pipable. Oh, but  the following is not correct in C++, is pseudo code, isn't it?
```
template<class T, class F>
pipable constexpr T tap(T&& x, const F& f);
```

**Comment by pfultz2** [comment]
> What I see is that tapwith two arguments return a pipable

It doesn't return a pipable, it returns `T`. `pipable` is just an annotation(like `constexpr`).

> Oh, but the following is not correct in C++, is pseudo code, isn't it?

I show all the functions as pseudo-signatures even though they are function objects because its easier to read.

**Comment by viboes** [comment]
This is why I created an issue to request for a section that explain how the reference documentation is documented.

I find troubling however that the signature in the documentation has two parameter and it can be used with one. More explanation are needed.

**Comment by pfultz2** [comment]
I added an explanation of function signatures in the library.
