### ISSUE TITLE
the index must contain all the function and macros

### ISSUE THREAD

**Issue by viboes** [pfultz2/Fit#80]
Some times you group several function in one page with a single index entry. I can understand that there is only one page for several functions but the index must contain all the entries.

**Comment by pfultz2** [comment]
There is no index, and there is no simple tool to generate an index in C++. Each entry is per header file. That is why some entries are grouped together.

**Comment by viboes** [comment]
I'm not talking of generating a index. I'm talking about having access to all the functions of the library.

If the an entry is corresponds to a file this must be stated clearly on how to read this documentation.

Or maybe it is better to add in the entries the file name.

**Comment by pfultz2** [comment]
I may be improving this to allow for a further detailed table of contents. This is pending a pull request from mkdocs [here](https://github.com/mkdocs/mkdocs/pull/851).

**Comment by pfultz2** [comment]
So now almost everything is indexed now with more detail.
