### ISSUE TITLE
protect() docs need an example and semantics

### ISSUE THREAD

**Issue by tzlaine** [pfultz2/Fit#89]
Preferably, the sample code should show what would happen with or without protecting a particular function call.

**Comment by viboes** [comment]
The semantics is missing also.

**Comment by pfultz2** [comment]
I've added an example. It is still missing semantics. The lazy adaptor is missing semantics as well. I am not sure the best way to show the semantics. I'll probably need to use placeholders, so something like this:

```cpp
lazy(f)(lazy(g)(_1))(x) == f(g(x))
lazy(f)(protect(lazy(g)(_1)))() == f(lazy(g)(_1))
```

I am not sure it is the clearest, though.
