### ISSUE TITLE
alias needs a motivating example

### ISSUE THREAD

**Issue by tzlaine** [pfultz2/Fit#95]
It's not at all clear why I'd use it, so it needs motivation or an example.  Otherwise, it should perhaps remain an implementation detail.

**Comment by pfultz2** [comment]
It is rather general-purpose. However, I do use this outside of the Fit library so I don't want to leave it as an implementation detail. Some examples where I use this:

1. Tag elements with a key to build an associative sequence

2. Tag the unit functions of a monad, so the monadic type can be deduced. 

Either one of these use cases don't lead to a simple motivating example, that is why I don't have a good example, yet. 

Plus, there are probably other examples of tagging types. I think I remember someone(maybe @viboes?) writing a `tagged` template for another library at some point that worked in a similar way.

**Comment by viboes** [comment]
Yes this is something that belong to a utility library.

If not used internally by the library I believe that it should removed.

**Comment by pfultz2** [comment]
> Yes this is something that belong to a utility library.

Well the Fit library is a utility library.

> If not used internally by the library I believe that it should removed.

It is used both internally and externally.
